### ISSUE TITLE
UUID for messages

### ISSUE THREAD

**Issue by zek** [musonza/chat#159]
I use this library for a mobile application and I generate uuid for every message on the mobile app. I need to save uuid of message to mark message as read, delivered etc.

Is it possible to add this feature?

**Comment by musonza** [comment]
Can you explain this more. I'm working on a major release and would like to include anything useful.

**Comment by Hirbod** [comment]
I think I know what he is proposing. I am building also a messaging app using React Native, and using React-Native-Gifted-Chat - and it required for the React Renderer to have a unique ID per message. So this package generate one for every message you append into the "virtual dom". The is a UUID. So if the messages is delivered (because to have more real time feeling we append the message even before its delivered), we generate a UUID/or any id you want, which is unique for that single message. So if we wan't to update that single message, without recreating the while view again, we need to bind it to a id, so the renderer will make a deep compare and will automatically detect, that for example, one message has changed. But the server doesn't know our particular UUID, it has an increment value, which the app doesn't know about. 

So, indeed, it would be amazing, to also submit a uuid which will be returned for every message.
The Flow should be: if UUID was sent along with the sent() Message, it should be saved, otherwise, one should be generated. And it should always be returned.

**Comment by zek** [comment]
Yeah this is what I am trying to do @Hirbod 

I use react-native-gifted-chat .

**Comment by Hirbod** [comment]
After digging deeper into this, saving a UUID is an  overhead and not needed. You can generate a UUID locally and pass it with your request as a parameter, and on your Laravel controller, grab that $request->msgid and pass it back as json in your return. I did this and this works perfectly now.
