### ISSUE TITLE
Get the senders in a conversation

### ISSUE THREAD

**Issue by ufeg02** [musonza/chat#32]
Is it possible to get the participants in a conversation without the authenticated user in Blade?

**Comment by musonza** [comment]
Why not just return the list in your controller excluding the authenticated user?

**Comment by ufeg02** [comment]
Sounds good! I use this code to get the messages. What's the best aproach to exclude the authenticated user?

 $this->messages = Chat::conversations()->for($user)->limit(25)->page(1)->get();

**Comment by musonza** [comment]
You want to exclude messages for the authenticated user? I'm not sure I understand.

**Comment by ufeg02** [comment]
No, I want the latest conversations of the authenticated user. If I show the list of conversations I don't want to show the authenticated user in the participant list.

**Comment by musonza** [comment]
I'm not sure what your code looks like to display the list. You know the authenticated user so how about put an if statement in your template logic to exclude the user. Some people may choose to show the user so this is something you should handle at your app code level. Let me know if that helps. Otherwise  show me what you template code looks like.

```
<ul>
@foreach ($participants as $user)
     @if ($user->id != Auth::user()->id)
    	<li>{{ $user->name }} ...</li>
     @endif
@endforeach
</ul>
```

**Comment by ufeg02** [comment]
Thank you!
